<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../plugin.props" />

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>HintServiceMeow.Tests</RootNamespace>
    <AssemblyName>HintServiceMeow.Tests</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <IsCodedUITest>False</IsCodedUITest>
    <TestProjectType>UnitTest</TestProjectType>
    <Configurations>Debug;ExiledPublish;Release;Publish</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ExiledPublish|x64'">
    <AssemblyName>HintServiceMeow.Test-Exiled</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="3.10.0" />
    <PackageReference Include="Northwood.LabAPI" Version="1.1.5" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HintServiceMeow\HintServiceMeow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>