<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../plugin.props" />

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>HintServiceExample</RootNamespace>
    <AssemblyName>HintServiceExample</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;ExiledPublish;Release;Publish</Configurations>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ExiledPublish|x64'">
    <AssemblyName>HintServiceExample-Exiled</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="1.1.7" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule" HintPath="..\Dependencies\UnityEngine.CoreModule.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HintServiceMeow\HintServiceMeow.csproj">
      <Project>{097b585f-438d-4d50-a8ac-0fe0e3a7de77}</Project>
      <Name>HintServiceMeow</Name>
    </ProjectReference>
  </ItemGroup>
</Project>