<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../plugin.props" />

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>HintServiceExample</RootNamespace>
    <AssemblyName>HintServiceExample</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <Configurations>Debug;ExiledPublish;Release;Publish</Configurations>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <ErrorReport>prompt</ErrorReport>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Publish|AnyCPU'">
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'ExiledPublish|AnyCPU'">
    <AssemblyName>HintServiceMeow-Exiled</AssemblyName>
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <Optimize>true</Optimize>
    <ErrorReport>prompt</ErrorReport>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="$(LabAPIVersion)" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\Dependencies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule" HintPath="..\Dependencies\UnityEngine.CoreModule.dll" Private="False" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HintServiceMeow\HintServiceMeow.csproj">
      <Project>{097b585f-438d-4d50-a8ac-0fe0e3a7de77}</Project>
      <Name>HintServiceMeow</Name>
    </ProjectReference>
  </ItemGroup>
</Project>